import Foundation

/// Owns the marker-delimited block the app generates inside the user's config
/// file. Everything outside the markers is the user's freeform area.
public enum ManagedRegion {
    public static let beginLine =
        "# >>> yabai-dockstack:managed BEGIN — generated by the app; edit in Settings, not here >>>"
    public static let endLine =
        "# <<< yabai-dockstack:managed END <<<"

    private static func isBegin(_ l: Substring) -> Bool { l.hasPrefix("# >>> yabai-dockstack:managed BEGIN") }
    private static func isEnd(_ l: Substring) -> Bool { l.hasPrefix("# <<< yabai-dockstack:managed END") }

    public static func extract(from text: String) -> String? {
        let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
        guard let b = lines.firstIndex(where: isBegin),
              let e = lines.firstIndex(where: isEnd), e > b else { return nil }
        let body = lines[(b + 1)..<e]
        return body.joined(separator: "\n")
    }

    public static func replace(in text: String, with body: String) -> String {
        let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
        let regionLines = [beginLine, body, endLine]
        if let b = lines.firstIndex(where: isBegin),
           let e = lines.firstIndex(where: isEnd), e > b {
            var kept = Array(lines)
            kept.replaceSubrange(b...e, with: regionLines.map { Substring($0) })
            return normalize(kept.map(String.init).joined(separator: "\n"))
        }
        // Append a fresh region at end, separated by a blank line.
        let base = text.isEmpty ? "" : (text.hasSuffix("\n") ? text : text + "\n")
        return normalize(base + "\n" + regionLines.joined(separator: "\n"))
    }

    private static func normalize(_ s: String) -> String {
        s.hasSuffix("\n") ? s : s + "\n"
    }
}
