import Foundation

/// Owns the marker-delimited block the app generates inside the user's config
/// file. Everything outside the markers is the user's freeform area.
public enum ManagedRegion {
    public static let beginLine =
        "# >>> yabai-dockstack:managed BEGIN — generated by the app; edit in Settings, not here >>>"
    public static let endLine =
        "# <<< yabai-dockstack:managed END <<<"

    private static func isBegin(_ l: Substring) -> Bool { l.hasPrefix("# >>> yabai-dockstack:managed BEGIN") }
    private static func isEnd(_ l: Substring) -> Bool { l.hasPrefix("# <<< yabai-dockstack:managed END") }

    public static func isBeginMarker(_ line: String) -> Bool {
        line.hasPrefix("# >>> yabai-dockstack:managed BEGIN")
    }
    public static func isEndMarker(_ line: String) -> Bool {
        line.hasPrefix("# <<< yabai-dockstack:managed END")
    }

    /// True when the markers are present but not a single clean ordered pair
    /// (e.g. duplicate BEGIN/END or END before BEGIN). A clean file has either
    /// zero markers or exactly one ordered BEGIN/END pair.
    public static func hasMalformedMarkers(in text: String) -> Bool {
        let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
        let begins = lines.filter(isBegin).count
        let ends = lines.filter(isEnd).count
        if begins == 0 && ends == 0 { return false }
        if begins == 1 && ends == 1 {
            let b = lines.firstIndex(where: isBegin)!
            let e = lines.firstIndex(where: isEnd)!
            return e <= b
        }
        return true
    }

    public static func extract(from text: String) -> String? {
        let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
        guard let b = lines.firstIndex(where: isBegin),
              let e = lines.firstIndex(where: isEnd), e > b else { return nil }
        let body = lines[(b + 1)..<e]
        return body.joined(separator: "\n")
    }

    public static func replace(in text: String, with body: String) -> String {
        let lines = text.split(separator: "\n", omittingEmptySubsequences: false)
        let regionLines = [beginLine, body, endLine]
        if let b = lines.firstIndex(where: isBegin),
           let e = lines.firstIndex(where: isEnd), e > b {
            var kept = Array(lines)
            kept.replaceSubrange(b...e, with: regionLines.map { Substring($0) })
            return normalize(kept.map(String.init).joined(separator: "\n"))
        }
        // Append a fresh region at end, separated by a blank line.
        let base = text.isEmpty ? "" : (text.hasSuffix("\n") ? text : text + "\n")
        return normalize(base + "\n" + regionLines.joined(separator: "\n"))
    }

    private static func normalize(_ s: String) -> String {
        s.hasSuffix("\n") ? s : s + "\n"
    }
}
